### ISSUE TITLE
delegate-status "Resigned" is not working

### ISSUE THREAD

**Issue by mtaylan** [unik-name/explorer#84]
https://explorer.unikname.network/delegate-status **Resigned** link does not produce an output. 
Also https://api.uns.network/api/v2/delegates?type=resigned gives **Internal server error 500**.

**Comment by peterjah** [comment]
Hi @mtaylan thank you for openning this issue.
The problem is identified and a fix is available here:
https://github.com/unik-name/unn-core/pull/336
It should be available soon in the next UNN-Core release
