### ISSUE TITLE
The explorer doesn't handle properly multipayments transactions 

### ISSUE THREAD

**Issue by arktoshidotcom** [unik-name/explorer#86]
mtaylan and I've just found a bug (maybe?) in Explorer. Please take a look at this TX (multiple payments):
https://explorer.unikname.network/transaction/c3608a3d21d45f4db41e7ae18c92f13e0cab811a8d1b462a1d1e453f6603eb1e

arktoshi delegate sent 11.177 UNIK to this wallet, but it shows <1 UNIK. The explorer shows wrong amount I believe.
https://explorer.unikname.network/wallets/USEGp6CZ5HNkbSB4F5vdTnowJGZT9iR86B

And this tx doesn't appear on My Unikname App as normal tx

**Comment by peterjah** [comment]
Hi @arktoshidotcom thank you for opening this issue.
A fix has been pushed for the explorer amount column.
https://github.com/unik-name/explorer/commit/abd7ac0aca3cc76bb0ade8f4631a56c48a8e3410

About My Unikname App, the multipayment transaction is not supported yet, so it won't appear in your wallet transaction. This will be done sooner or later!
